USE snikers_db;
ALTER TABLE orders 
MODIFY COLUMN status ENUM('PENDING','PAID','SHIPPED','IN_TRANSIT','DELIVERED','CANCELLED','COMPLETED','REFUND_REQUESTED','REFUND_APPROVED','REFUND_REJECTED') DEFAULT NULL;